# Generated by Django 4.0.4 on 2022-06-06 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('Custname', models.CharField(max_length=20)),
                ('Custid', models.IntegerField(primary_key=True, serialize=False)),
                ('Address', models.CharField(max_length=20)),
                ('PanCard', models.CharField(max_length=20)),
                ('AdharcardNo', models.CharField(max_length=20)),
                ('Phno', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('Staffname', models.CharField(max_length=20)),
                ('Staffid', models.IntegerField(primary_key=True, serialize=False)),
                ('Address', models.CharField(max_length=20)),
                ('PanCard', models.CharField(max_length=20)),
                ('AdharcardNo', models.CharField(max_length=20)),
                ('Phno', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('VehicleType', models.CharField(max_length=20)),
                ('VehicleNo', models.IntegerField(primary_key=True, serialize=False)),
                ('Company', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('Stock', models.IntegerField()),
                ('Stockid', models.IntegerField(primary_key=True, serialize=False)),
                ('VehicleNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showroom_app.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Bookingbystaff',
            fields=[
                ('Bookingid', models.IntegerField(primary_key=True, serialize=False)),
                ('Staffid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showroom_app.staff')),
                ('Stockid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showroom_app.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Bookingbycustomer',
            fields=[
                ('Bookingid', models.IntegerField(primary_key=True, serialize=False)),
                ('Custid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showroom_app.customer')),
                ('Stockid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showroom_app.stock')),
            ],
        ),
    ]
