# Generated by Django 4.0.4 on 2022-06-06 16:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('showroom_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='mail',
            field=models.CharField(default=datetime.datetime(2022, 6, 6, 16, 25, 54, 412277, tzinfo=utc), max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='pwd',
            field=models.CharField(default=datetime.datetime(2022, 6, 6, 16, 25, 59, 747795, tzinfo=utc), max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='mail',
            field=models.CharField(default=datetime.datetime(2022, 6, 6, 16, 26, 2, 559288, tzinfo=utc), max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='pwd',
            field=models.CharField(default=datetime.datetime(2022, 6, 6, 16, 26, 4, 939365, tzinfo=utc), max_length=20),
            preserve_default=False,
        ),
    ]
