# Generated by Django 4.0.4 on 2022-06-07 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showroom_app', '0002_customer_mail_customer_pwd_staff_mail_staff_pwd'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VehicleName', models.CharField(max_length=20)),
                ('VehiclePrice', models.IntegerField()),
                ('VehicleDesc', models.CharField(max_length=100)),
                ('VehicleImg', models.ImageField(upload_to='static\\images')),
                ('VehicleNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showroom_app.vehicle', unique=True)),
            ],
        ),
    ]
