# Generated by Django 4.0.4 on 2022-06-07 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showroom_app', '0003_vehicledetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicledetails',
            name='id',
        ),
        migrations.AlterField(
            model_name='vehicledetails',
            name='VehicleNo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='showroom_app.vehicle'),
        ),
    ]
