# Generated by Django 4.0.4 on 2022-06-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom_app', '0004_remove_vehicledetails_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledetails',
            name='VehicleImg',
            field=models.ImageField(upload_to='showroom\\static\\images'),
        ),
    ]
