# Generated by Django 4.0.5 on 2022-06-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom_app', '0005_alter_vehicledetails_vehicleimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Feedback', models.TextField()),
            ],
        ),
    ]
